/**
 * Chord Templates for Recognition
 *
 * Pre-computed chord templates used for matching chromagram vectors
 * to chord types. Each template is a 12-bin array representing the
 * expected energy in each pitch class.
 *
 * Pitch class indices: C=0, C#=1, D=2, D#=3, E=4, F=5, F#=6, G=7, G#=8, A=9, A#=10, B=11
 */

import type { ChordQuality } from '../../types/music';
import type { ChromaVector, ChordTemplate } from '../../types/audioAnalysis';

// Root note names in pitch class order
export const PITCH_CLASS_NAMES = ['C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'B'] as const;

// Map note names to pitch class indices (including flats)
export const NOTE_TO_PITCH_CLASS: Record<string, number> = {
  'C': 0, 'C#': 1, 'Db': 1, 'D': 2, 'D#': 3, 'Eb': 3,
  'E': 4, 'Fb': 4, 'E#': 5, 'F': 5, 'F#': 6, 'Gb': 6,
  'G': 7, 'G#': 8, 'Ab': 8, 'A': 9, 'A#': 10, 'Bb': 10,
  'B': 11, 'Cb': 11, 'B#': 0,
};

/**
 * Base chord templates relative to C root (pitch class 0)
 * Values represent expected energy (1 = present, 0 = absent)
 * Index represents pitch class (0=C, 1=C#, etc.)
 */
export const BASE_CHORD_TEMPLATES: Record<ChordQuality, ChromaVector> = {
  // Basic triads
  major:      [1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0], // 1 - 3 - 5
  minor:      [1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0], // 1 - b3 - 5
  diminished: [1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0], // 1 - b3 - b5
  augmented:  [1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0], // 1 - 3 - #5

  // Seventh chords
  dominant7:  [1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0], // 1 - 3 - 5 - b7
  major7:     [1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1], // 1 - 3 - 5 - 7
  minor7:     [1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0], // 1 - b3 - 5 - b7
  dim7:       [1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0], // 1 - b3 - b5 - bb7
  'half-dim7': [1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0], // 1 - b3 - b5 - b7

  // Suspended chords
  sus2:       [1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0], // 1 - 2 - 5
  sus4:       [1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0], // 1 - 4 - 5

  // Extended chords
  add9:       [1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0], // 1 - 2 - 3 - 5

  // Power chord (for rock/metal detection)
  power:      [1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0], // 1 - 5
};

/**
 * Quality to chord suffix mapping for display
 */
export const QUALITY_TO_SUFFIX: Record<ChordQuality, string> = {
  major: '',
  minor: 'm',
  diminished: 'dim',
  augmented: 'aug',
  dominant7: '7',
  major7: 'maj7',
  minor7: 'm7',
  dim7: 'dim7',
  'half-dim7': 'm7b5',
  sus2: 'sus2',
  sus4: 'sus4',
  add9: 'add9',
  power: '5',
};

/**
 * Parse chord name suffix back to quality
 */
export function suffixToQuality(suffix: string): ChordQuality | 'unknown' {
  const normalized = suffix.toLowerCase();

  if (normalized === '' || normalized === 'maj') return 'major';
  if (normalized === 'm' || normalized === 'min') return 'minor';
  if (normalized === 'dim' || normalized === '°' || normalized === 'o') return 'diminished';
  if (normalized === 'aug' || normalized === '+') return 'augmented';
  if (normalized === '7' || normalized === 'dom7') return 'dominant7';
  if (normalized === 'maj7' || normalized === 'm7' || normalized === 'Δ7') return 'major7';
  if (normalized === 'm7' || normalized === 'min7' || normalized === '-7') return 'minor7';
  if (normalized === 'dim7' || normalized === '°7') return 'dim7';
  if (normalized === 'm7b5' || normalized === 'ø' || normalized === 'ø7') return 'half-dim7';
  if (normalized === 'sus2') return 'sus2';
  if (normalized === 'sus4' || normalized === 'sus') return 'sus4';
  if (normalized === 'add9') return 'add9';
  if (normalized === '5') return 'power';

  return 'unknown';
}

/**
 * Rotate an array by the given number of positions
 * Used to transpose chord templates to different roots
 */
function rotateArray<T>(arr: T[], positions: number): T[] {
  const n = arr.length;
  const p = ((positions % n) + n) % n;
  return [...arr.slice(p), ...arr.slice(0, p)];
}

/**
 * Generate chord name from root and quality
 */
function formatChordName(root: string, quality: ChordQuality): string {
  return root + QUALITY_TO_SUFFIX[quality];
}

/**
 * All chord templates for all roots
 * Generated by rotating base templates to each pitch class
 */
let allTemplatesCache: Map<string, ChordTemplate> | null = null;

/**
 * Generate all chord templates for all 12 roots
 */
export function getAllChordTemplates(): Map<string, ChordTemplate> {
  if (allTemplatesCache) {
    return allTemplatesCache;
  }

  const templates = new Map<string, ChordTemplate>();

  for (const [quality, baseTemplate] of Object.entries(BASE_CHORD_TEMPLATES)) {
    for (let rootIndex = 0; rootIndex < 12; rootIndex++) {
      // Rotate template to match root
      const rotatedTemplate = rotateArray(baseTemplate, rootIndex) as ChromaVector;
      const chordName = formatChordName(PITCH_CLASS_NAMES[rootIndex], quality as ChordQuality);

      templates.set(chordName, {
        name: chordName,
        quality: quality as ChordQuality,
        template: rotatedTemplate,
      });
    }
  }

  allTemplatesCache = templates;
  return templates;
}

/**
 * Get template for a specific chord
 */
export function getChordTemplate(chordName: string): ChordTemplate | undefined {
  return getAllChordTemplates().get(chordName);
}

/**
 * Get all templates for a specific quality (all roots)
 */
export function getTemplatesByQuality(quality: ChordQuality): ChordTemplate[] {
  const allTemplates = getAllChordTemplates();
  const result: ChordTemplate[] = [];

  for (const template of allTemplates.values()) {
    if (template.quality === quality) {
      result.push(template);
    }
  }

  return result;
}

/**
 * Get all chord names in detection order
 * Priority: basic triads first, then 7ths, then extensions
 */
export function getChordNamesInPriority(): string[] {
  const priorityQualities: ChordQuality[] = [
    // Most common first
    'major', 'minor',
    // 7th chords
    'dominant7', 'major7', 'minor7',
    // Less common
    'sus4', 'sus2',
    'diminished', 'augmented',
    'half-dim7', 'dim7',
    'add9',
    'power',
  ];

  const names: string[] = [];

  for (const quality of priorityQualities) {
    for (let rootIndex = 0; rootIndex < 12; rootIndex++) {
      names.push(formatChordName(PITCH_CLASS_NAMES[rootIndex], quality));
    }
  }

  return names;
}
